server:
  port: 8082

spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://localhost:5432/crisisgrid
    username: postgres
    password: xxxxxxxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: resource-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

kafka:
  topic:
    crisis-events: crisis-events
